//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowsy.Specification.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Flowsy.Specification.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ValueDoesNotExceedNCharacters {
            get {
                return ResourceManager.GetString("ValueDoesNotExceedNCharacters", resourceCulture);
            }
        }
        
        internal static string ValueMustNotExceedNCharacters {
            get {
                return ResourceManager.GetString("ValueMustNotExceedNCharacters", resourceCulture);
            }
        }
        
        internal static string ValueIsAtLeastNCharactersLong {
            get {
                return ResourceManager.GetString("ValueIsAtLeastNCharactersLong", resourceCulture);
            }
        }
        
        internal static string ValueMustBeAtLeastNCharactersLong {
            get {
                return ResourceManager.GetString("ValueMustBeAtLeastNCharactersLong", resourceCulture);
            }
        }
        
        internal static string XIsNotAnEmptyValue {
            get {
                return ResourceManager.GetString("XIsNotAnEmptyValue", resourceCulture);
            }
        }
        
        internal static string TheValueIsEmpty {
            get {
                return ResourceManager.GetString("TheValueIsEmpty", resourceCulture);
            }
        }
        
        internal static string XIsNotANullValue {
            get {
                return ResourceManager.GetString("XIsNotANullValue", resourceCulture);
            }
        }
        
        internal static string TheValueIsNull {
            get {
                return ResourceManager.GetString("TheValueIsNull", resourceCulture);
            }
        }
        
        internal static string ValueDoesNotConsistOnlyOfWhitespaceCharacters {
            get {
                return ResourceManager.GetString("ValueDoesNotConsistOnlyOfWhitespaceCharacters", resourceCulture);
            }
        }
        
        internal static string ValueConsistsOnlyOfWhitespaceCharacters {
            get {
                return ResourceManager.GetString("ValueConsistsOnlyOfWhitespaceCharacters", resourceCulture);
            }
        }
        
        internal static string BothSpecificationsWereSatisfied {
            get {
                return ResourceManager.GetString("BothSpecificationsWereSatisfied", resourceCulture);
            }
        }
        
        internal static string NoneOfTheSpecificationsWasSatisfied {
            get {
                return ResourceManager.GetString("NoneOfTheSpecificationsWasSatisfied", resourceCulture);
            }
        }
        
        internal static string TheTargetSpecificationWasNotSatisfied {
            get {
                return ResourceManager.GetString("TheTargetSpecificationWasNotSatisfied", resourceCulture);
            }
        }
        
        internal static string TheTargetSpecificationWasSatisfied {
            get {
                return ResourceManager.GetString("TheTargetSpecificationWasSatisfied", resourceCulture);
            }
        }
        
        internal static string AtLeastOneOfTheSpecificationsWasSatisfied {
            get {
                return ResourceManager.GetString("AtLeastOneOfTheSpecificationsWasSatisfied", resourceCulture);
            }
        }
    }
}
